routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Controladores del apartado CRUD.
use App\Http\Controllers\JornadasController;
use App\Http\Controllers\DocentesController;
use App\Http\Controllers\CentrosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\AlumnosController;
use App\Http\Controllers\EmpresasController;
use App\Http\Controllers\AulasController;
use App\Http\Controllers\SesionesController;
use App\Http\Controllers\TitulacionesController;
use App\Http\Controllers\Alumnos_Empresas_JornadasController;
use App\Http\Controllers\PDFController;


//Controlador del calendario. 
use App\Http\Controllers\FullCalendarController;

//Controlador necesario para la parte de importación y exportación. 
use App\Http\Controllers\ImportExportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Redireccionamiento al inicio en caso de error 404. 
Route::fallback(function () {

    return redirect('/inicio');

});
// Página inicial de nuestra aplicación: deriva en gestión de datos y en calendario. 
Route::get('/inicio', function () {
    return view('home');
});

// Página previa a la gestión de las jornadas y vinculación, permite gestionar información necesaria. 
Route::get('/intruccionesjornadas', function () {
    return view('Jornadas.previous');
});

// Control de importación y exportación, usado en ambos apartados de la aplicación. 
Route::get('Alumnosmasivo', [ImportExportController::class, 'importExportView']);
Route::get('export', [ImportExportController::class, 'export'])->name('export');
Route::post('import', [ImportExportController::class, 'import'])->name('import');

// Apartado 1 de la aplicación: gestión de datos, se compone de una vista inicial, que nos mete en el index de las tablas y en consultas seleccionadas. 
Route::get('/gestiondedatos', function () {
    return view('data');
});
// Para el funcionamiento de todo el método CRUD de los modelos y las diferentes consultas es necesario la utilización de sus controladores y rutas específicas. 
Route::resource('Jornadas', JornadasController::class);
Route::resource('Docentes', DocentesController::class);
Route::resource('Centros', CentrosController::class);
Route::resource('Cursos', CursosController::class);
Route::resource('Alumnos', AlumnosController::class);
Route::resource('Empresas', EmpresasController::class);
Route::resource('Aulas', AulasController::class);
Route::resource('Sesiones', SesionesController::class);
Route::resource('Titulaciones', TitulacionesController::class);
Route::resource('Alumnos_Empresas_Jornadas', Alumnos_Empresas_JornadasController::class);
Route::get('Jornadas/select_aulas/{centro}', [FullCalendarController::class, 'sacaAulas']);

// Apartado 2 de la aplicación: calendario, se compone de una vista inicial del calendario, así como de los métodos necesarios para la creación de las jornadas y su gestión. 
Route::get('/calendario', function () {
    return view('fullcalendar');
});
// Para el sistema de exportación a PDF es necesario un paquete extra.
Route::get('cartel/{id}', [PDFController::class, 'cartel']); // Generación del cartel del curso. 
Route::get('material/{id}', [PDFController::class, 'material']); // Generación del documento de material del curso. 
Route::get('diplomas/{id}', [PDFController::class, 'diplomas']); // Generación de los diplomas del curso. 
Route::get('evaluacion/{id}', [PDFController::class, 'evaluacion']); // Generación del control de aptos.
Route::get('asistencia/{id}', [PDFController::class, 'asistencia']); // Generación del control de asistencia del curso.  
Route::get('fotosRGD/{id}', [PDFController::class, 'fotosRGD']); // Generación del documento de autorización de imágenes.
Route::get('registroalumno/{id}', [PDFController::class, 'registroalumno']); // Generación del documento de registro del alumno. 

app/Models/Empresas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Empresas extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [

        'id',

        'nombre',

        'denom_comercial',

        'telefono',

        'email',

        'codigo_postal',

        'localidades_id'

    ];

    /**
     * 
     * Se establece una relación 1:N con la localidad. 
     * 
     */
    public function Localidades()
    {
        return $this->hasOne(Localidades::class, 'localidades_id');
    }

    /**
     * 
     * Se establece una relación con la ternaria. 
     * 
     */
    public function Alumnos_Empresas_Jornadas()
    {
        return $this->hasMany(Alumnos_Empresas_Jornadas::class);
    }
}

app/Http/Controllers/EmpresasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Empresas;
use App\Models\Localidades;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EmpresasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $localidades = Localidades::all();

        return view('Empresas.index',  ['empresas' => DB::table('empresas')->paginate(10)], [ 'localidades' => $localidades]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $localidades = Localidades::all();

        return view('Empresas.create', ['localidades' => $localidades]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([

            'nombre'  => 'required',

            'telefono' => 'required',

        ]);

        Empresas::create($request->all());

        return redirect()->route('Empresas.index')->with('success', 'Nueva empresa dada de alta.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Empresas  $empresas
     * @return \Illuminate\Http\Response
     */
    public function show(Empresas $empresas)
    {
        return redirect('/inicio');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $empresa = Empresas::findOrFail($id);

        $localidades = Localidades::all();

        return view('Empresas.edit', ['empresa' => $empresa, 'localidades' => $localidades]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = array_slice($request->all(), 2);

        Empresas::whereId($id)->update($data);

        $request->session()->flash('correcto', 'Se ha editado el registro.');

        return redirect('Empresas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Empresas  $empresas
     * @return \Illuminate\Http\Response
     * @param  \Illuminate\Http\Request  $request
     */
    public function destroy($id, Request $request)
    {
        Empresas::where('id', $id)->delete();

        $request->session()->flash('correcto', 'Se ha borrado el registro.');

        return redirect('Empresas');
    }
}

resources/views/Empresas/create.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Dar de alta a una nueva empresa. </h2>
        </div>
    </div>
</div>

<br>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('Empresas.store') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Nombre de la empresa:</strong>
                <input type="text" name="nombre" class="form-control" placeholder="Nombre de la empresa">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Denominación comercial:</strong>
                <input type="text" name="denom_comercial" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2">
            <div class="form-group">
                <strong>Teléfono:</strong>
                <input type="text" name="telefono" class="form-control" placeholder="Dato obligatorio">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2">
            <div class="form-group">
                <strong>Código postal:</strong>
                <input type="text" name="codigo_postal" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <label for="cars">Elija una localidad:</label>
            <select name="localidades_id" id="localidades_id">
                @foreach ($localidades as $localidad)
                <option value="{{ $localidad->id }}"> {{ $localidad->localidad }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary"> Dar de alta </button>
        </div>
    </div>


</form>

@endsection

resources/views/Empresas/destroy.blade.php
<div class="modal" tabindex="-1" role="dialog" id="modal-delete-{{$empresa->id}}">
    <form method="POST" action="{{url('/Empresas/delete').'/'.$empresa->id}}" style="display:inline">
        @method('DELETE')
        @csrf
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Eliminar registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p> El registro puede tener jornadas asociadas y se perderá información sobre ellas ¿Está seguro de querer borrar esta empresa? </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/Empresas/edit.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Modificando datos de la empresa {{ $empresa->nombre }}. </h2>
        </div>
    </div>
</div>

<br>


<div class="row" style="margin-top:40px">
<form method="POST" enctype="multipart/form-data" action="{{url('Empresas/'.$empresa->id)}}" style="display:inline">
{{-- TODO: Abrir el formulario e indicar el método POST --}}
        @method('PUT')
        {{-- TODO: Protección contra CSRF --}}
        @csrf
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Nombre de la empresa:</strong>
                <input type="text" name="nombre" class="form-control" value="{{ $empresa->nombre }}">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Denominación comercial:</strong>
                <input type="text" name="denom_comercial" class="form-control" value="{{ $empresa->denom_comercial }}">
            </div>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2">
            <div class="form-group">
                <strong>Teléfono:</strong>
                <input type="text" name="telefono" class="form-control" value="{{ $empresa->telefono }}">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" value="{{ $empresa->email }}">
            </div>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2">
            <div class="form-group">
                <strong>Código postal:</strong>
                <input type="text" name="codigo_postal" class="form-control" value="{{ $empresa->codigo_postal}}">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <label for="cars">Elija una localidad:</label>
            <select name="localidades_id" id="localidades_id">
                @foreach ($localidades as $localidad)
                <option value="{{ $localidad->id }}"> {{ $localidad->localidad }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Realizar la modificación </button>
        </div>
    </div>


</form>

@endsection

resources/views/Empresas/index.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Empresas </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('Empresas.create') }}"> Dar de alta a una nueva empresa </a>
        </div>
    </div>
</div>

<br>
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="row">
    <table class="table table-striped table-bordered">
        <tr>
            <th> Nombre </th>
            <th> Denominación comercial </th>
            <th> Código postal </th>
            <th> Localidad </th>
            <th> Email </th>
            <th> Teléfono </th>
            <th> Opciones </th>
        </tr>
        @foreach ($empresas as $empresa)
        <tr>
            <td> {{ $empresa->nombre }} </td>
            <td> {{$empresa->denom_comercial}}  </td>
            <td> {{$empresa->codigo_postal}} </td>
            <td> {{$localidades[$empresa->localidades_id - 1]->localidad}} </td>
            <td> {{$empresa->email}} </td>
            <td> {{$empresa->telefono}} </td>
            <td>

                <form method="POST" action=" {{  url( '/Empresas/' .$empresa->id ) }}" style="display:inline">

                    <a class="btn btn-success" href="{{ route('Empresas.edit',$empresa->id) }}"> Editar </a>

                    @method('DELETE')

                    @csrf

                    @include('Empresas.destroy')

                    <a href="" data-target="#modal-delete-{{$empresa->id}}" data-toggle="modal" class="btn btn-danger">Eliminar</a>

                </form>
            </td>
        </tr>
        @endforeach
    </table>
</div>

@endsection