routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Controladores del apartado CRUD.
use App\Http\Controllers\JornadasController;
use App\Http\Controllers\DocentesController;
use App\Http\Controllers\CentrosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\AlumnosController;
use App\Http\Controllers\EmpresasController;
use App\Http\Controllers\AulasController;
use App\Http\Controllers\SesionesController;
use App\Http\Controllers\TitulacionesController;
use App\Http\Controllers\Alumnos_Empresas_JornadasController;
use App\Http\Controllers\PDFController;


//Controlador del calendario. 
use App\Http\Controllers\FullCalendarController;

//Controlador necesario para la parte de importación y exportación. 
use App\Http\Controllers\ImportExportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Redireccionamiento al inicio en caso de error 404. 
Route::fallback(function () {

    return redirect('/inicio');

});
// Página inicial de nuestra aplicación: deriva en gestión de datos y en calendario. 
Route::get('/inicio', function () {
    return view('home');
});

// Página previa a la gestión de las jornadas y vinculación, permite gestionar información necesaria. 
Route::get('/intruccionesjornadas', function () {
    return view('Jornadas.previous');
});

// Control de importación y exportación, usado en ambos apartados de la aplicación. 
Route::get('Alumnosmasivo', [ImportExportController::class, 'importExportView']);
Route::get('export', [ImportExportController::class, 'export'])->name('export');
Route::post('import', [ImportExportController::class, 'import'])->name('import');

// Apartado 1 de la aplicación: gestión de datos, se compone de una vista inicial, que nos mete en el index de las tablas y en consultas seleccionadas. 
Route::get('/gestiondedatos', function () {
    return view('data');
});
// Para el funcionamiento de todo el método CRUD de los modelos y las diferentes consultas es necesario la utilización de sus controladores y rutas específicas. 
Route::resource('Jornadas', JornadasController::class);
Route::resource('Docentes', DocentesController::class);
Route::resource('Centros', CentrosController::class);
Route::resource('Cursos', CursosController::class);
Route::resource('Alumnos', AlumnosController::class);
Route::resource('Empresas', EmpresasController::class);
Route::resource('Aulas', AulasController::class);
Route::resource('Sesiones', SesionesController::class);
Route::resource('Titulaciones', TitulacionesController::class);
Route::resource('Alumnos_Empresas_Jornadas', Alumnos_Empresas_JornadasController::class);
Route::get('Jornadas/select_aulas/{centro}', [FullCalendarController::class, 'sacaAulas']);

// Apartado 2 de la aplicación: calendario, se compone de una vista inicial del calendario, así como de los métodos necesarios para la creación de las jornadas y su gestión. 
Route::get('/calendario', function () {
    return view('fullcalendar');
});
// Para el sistema de exportación a PDF es necesario un paquete extra.
Route::get('cartel/{id}', [PDFController::class, 'cartel']); // Generación del cartel del curso. 
Route::get('material/{id}', [PDFController::class, 'material']); // Generación del documento de material del curso. 
Route::get('diplomas/{id}', [PDFController::class, 'diplomas']); // Generación de los diplomas del curso. 
Route::get('evaluacion/{id}', [PDFController::class, 'evaluacion']); // Generación del control de aptos.
Route::get('asistencia/{id}', [PDFController::class, 'asistencia']); // Generación del control de asistencia del curso.  
Route::get('fotosRGD/{id}', [PDFController::class, 'fotosRGD']); // Generación del documento de autorización de imágenes.
Route::get('registroalumno/{id}', [PDFController::class, 'registroalumno']); // Generación del documento de registro del alumno. 

app/Models/Jornadas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jornadas extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [

        'id',

        'fecha_ini',

        'fecha_fin',

        'num_sesiones',

        'num_expediente',

        'entidad_organizadora',

        'nombre_comercial',

        'horario',

        'docentes_id',

        'cursos_id',

        'centros_id',

        'aulas_id'

    ];

    /**
     * 
     * Se establece una relación 1:N con los cursos. 
     * 
     */
    public function Cursos()
    {
        return $this->belongsTo(Cursos::class);
    }

    /**
     * 
     * Se establece una relación 1:N con los docentes. 
     * 
     */
    public function Docentes()
    {
        return $this->hasOne(Docentes::class, 'docentes_id');
    }

    /**
     * 
     * Se establece una relación 1:N con los centros. 
     * 
     */
    public function Centros()
    {
        return $this->hasOne(Centros::class, 'centros_id');
    }

    /**
     * 
     * Se establece una relación 1:N con las sesiones. 
     * 
     */
    public function Sesiones()
    {
        return $this->hasMany(Sesiones::class);
    }

    /**
     * 
     * Se establece una relación con la ternaria. 
     * 
     */
    public function Alumnos_Empresas_Jornadas()
    {
        return $this->hasMany(Alumnos_Empresas_Jornadas::class);
    }

    /**
     * 
     * Se establece una relación 1:N con el aula.  
     * 
     */
    public function Aulas()
    {
        return $this->hasOne(Aulas::class, 'aulas_id');
    }
}

app/Http/Controllers/JornadasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jornadas;
use App\Models\Docentes;
use App\Models\Cursos;
use App\Models\Centros;
use App\Models\Sesiones;
use App\Models\Localidades;
use App\Models\Titulaciones;
use App\Models\Aulas;
use App\Models\Alumnos;
use App\Models\Empresas;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class JornadasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $docentes = Docentes::all();

        $cursos = Cursos::all();

        $centros = Centros::all();

        $sesiones = Sesiones::all();

        $aulas = Aulas::all();

        $jornadas = Jornadas::all();

        return view(
            'Jornadas.index',

            ['jornadas' => DB::table('jornadas')->paginate(15)],

            [

                'docentes' => $docentes,

                'cursos' => $cursos,

                'centros' => $centros,

                'sesiones' => $sesiones,

                'aulas' => $aulas,

                'jornadas' => $jornadas

            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $centros = Centros::all();

        $docentes = Docentes::all();

        $cursos = Cursos::all();

        $aulas = Aulas::all();

        return view('Jornadas.create', [

            'docentes' => $docentes,

            'cursos' => $cursos,

            'centros' => $centros,

            'aulas' => $aulas
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([

            'fecha_ini'  => 'required',

            'fecha_fin' => 'required',

            'num_sesiones' => 'required',

            'num_expediente' => 'required',

            'entidad_organizadora'  => 'required',

            'nombre_comercial'  => 'required',

            'horario' => 'required'

        ]);

        Jornadas::create($request->all());

        return redirect()->route('Sesiones.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Datos generales de la jornada. 

        $jornada = Jornadas::findOrFail($id);

        $curso = Cursos::findOrFail($jornada->cursos_id);

        $sesiones = Sesiones::where('jornadas_id', '=', $jornada->id)->get();

        // Datos del centro. 

        $centro = Centros::findOrFail($jornada->centros_id);

        $aulas = Aulas::where('id', '=', $jornada->aulas_id)->get();

        $localidad_centro = Localidades::findOrFail($centro->localidades_id);

        //Datos del docente. 

        $docente = Docentes::findOrFail($jornada->docentes_id);

        $localidad_docente = Localidades::findOrFail($docente->localidades_id);

        $titulacion_docente = Titulaciones::findOrFail($docente->titulaciones_id);

        // Datos de todos los alumnos y su empresa. 

        $alumnos_empresas = DB::table('alumnos_empresas_jornadas')->where('jornadas_id', '=', $id)->get();

        $empresas = Empresas::all();

        $alumnos = Alumnos::all();

        return view(

            'Jornadas.show',

            [

                'jornada' => $jornada,

                'curso' => $curso,

                'sesiones' => $sesiones,

                'centro' => $centro,

                'aulas' => $aulas,

                'localidad_centro' => $localidad_centro,

                'docente' => $docente,

                'localidad_docente' => $localidad_docente,

                'titulacion_docente' => $titulacion_docente,

                'alumnos_empresas' => $alumnos_empresas,

                'empresas' => $empresas,

                'alumnos' => $alumnos

            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $docentes = Docentes::all();

        $cursos = Cursos::all();

        $centros = Centros::all();

        $sesiones = Sesiones::all();

        $jornada = Jornadas::findOrFail($id);

        return view(
            'Jornadas.edit',

            [
                'jornada' => $jornada,

                'docentes' => $docentes,

                'cursos' => $cursos,

                'centros' => $centros,

                'sesiones' => $sesiones
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = array_slice($request->all(), 2);

        Jornadas::whereId($id)->update($data);

        $request->session()->flash('correcto', 'Se ha editado el registro.');

        return redirect('Jornadas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Jornadas  $jornadas
     * @return \Illuminate\Http\Response
     * @param  \Illuminate\Http\Request  $request
     */
    public function destroy($id, Request $request)
    {
        Jornadas::where('id', $id)->delete();

        $request->session()->flash('correcto', 'Se ha borrado el registro.');

        return redirect('Jornadas');
    }

}

resources/views/Jornadas/create.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Registrar una nueva jornada. </h2>
        </div>
    </div>
</div>

<br>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('Jornadas.store') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong> Fecha de inicio:</strong>
                <input type="date" name="fecha_ini" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong> Fecha de fin:</strong>
                <input type="date" name="fecha_fin" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong> Número de sesiones:</strong>
                <input type="text" name="num_sesiones" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="form-group">
                <strong> Número de expediente:</strong>
                <input type="text" name="num_expediente" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="form-group">
                <strong> Entidad organizadora:</strong>
                <input type="text" name="entidad_organizadora" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="form-group">
                <strong> Nombre comercial:</strong>
                <input type="text" name="nombre_comercial" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="form-group">
                <strong> Horario:</strong>
                <input type="text" name="horario" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <label for="cars"> Docente:</label>
            <select name="docentes_id" id="docentes_id">
                <option value=""></option>
                @foreach ($docentes as $docente)
                <option value="{{ $docente->id }}"> {{ $docente->nombre }} {{ $docente->apellido_1 }} {{ $docente->apellido_2 }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <label for="cars"> Curso:</label>
            <select name="cursos_id" id="cursos_id">
                <option value=""></option>
                @foreach ($cursos as $curso)
                <option value="{{ $curso->id }}"> {{ $curso->nombre }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <label for="cars"> Centro:</label>
            <select name="centros_id" id="centros_id">
                <option value=""></option>
                @foreach ($centros as $centro)
                <option value="{{ $centro->id }}"> {{ $centro->nombre }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
            <label for="cars"> Aula:</label>
            <select name="aulas_id" id="aulas_id">
            </select>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary"> Dar de alta </button>
        </div>
    </div>

</form>

<script>
    $('#centros_id').on('change', function(e) {
        console.log(e);
        var centro = e.target.value;

        $.get('select_aulas/' + centro, function(data) {

            $('#aulas').empty();

            $.each(data, function(fetch, aulas) {
                console.log(data);
                for (i = 0; i < aulas.length; i++) {
                    $('#aulas_id').append('<option value="' + aulas[i].id + '">' + aulas[i].num + '</option>');
                }
            })
        })
    });
</script>

@endsection

resources/views/Jornadas/destroy.blade.php
<div class="modal" tabindex="-1" role="dialog" id="modal-delete-{{$jornada->id}}">
    <form method="POST" action="{{url('/Jornadas/delete').'/'.$jornada->id}}" style="display:inline">
        @method('DELETE')
        @csrf
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Eliminar registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p> El borrado de información es irreversible ¿desea continuar?  </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/Jornadas/edit.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Modificando jornada. </h2>
        </div>
    </div>
</div>

<div class="row" style="margin-top:40px">
    <form method="POST" enctype="multipart/form-data" action="{{url('Jornadas/'.$jornada->id)}}" style="display:inline">
        {{-- TODO: Abrir el formulario e indicar el método POST --}}
        @method('PUT')
        {{-- TODO: Protección contra CSRF --}}
        @csrf

        <div class="row">
            <div class="col-xs-2 col-sm-2 col-md-2">
                <div class="form-group">
                    <strong> Fecha de inicio:</strong>
                    <input type="date" name="fecha_ini" class="form-control" value="{{ $jornada->fecha_ini }}">
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2">
                <div class="form-group">
                    <strong> Fecha de fin:</strong>
                    <input type="date" name="fecha_fin" class="form-control" value="{{ $jornada->fecha_fin }}">
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="form-group">
                    <strong> Número de sesiones:</strong>
                    <input type="text" name="num_sesiones" class="form-control" value="{{ $jornada->num_sesiones }}">
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="form-group">
                    <strong> Número de expediente:</strong>
                    <input type="text" name="num_expediente" class="form-control" value="{{ $jornada->num_expediente }}">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong> Entidad organizadora:</strong>
                    <input type="text" name="entidad_organizadora" class="form-control" value="{{ $jornada->entidad_organizadora }}">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong> Nombre comercial:</strong>
                    <input type="text" name="nombre_comercial" class="form-control" value="{{ $jornada->nombre_comercial }}">
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2">
                <div class="form-group">
                    <strong> Horario:</strong>
                    <input type="text" name="horario" class="form-control" value="{{ $jornada->horario }}">
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <label for="cars">Docente:</label>
                <select name="docentes_id" id="docentes_id">
                    @foreach ($docentes as $docente)
                    <option value="{{ $docente->id }}"> {{ $docente->nombre }} {{ $docente->apellido_1}} {{ $docente->apellido_2 }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <label for="cars">Curso relacionado:</label>
                <select name="cursos_id" id="cursos_id">
                    @foreach ($cursos as $curso)
                    <option value="{{ $curso->id }}"> {{ $curso->nombre }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2">
                <label for="cars">Centro seleccionado:</label>
                <select name="centros_id" id="centros_id">
                    @foreach ($centros as $centro)
                    <option value="{{ $centro->id }}"> {{ $centro->nombre }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary"> Realizar la modificación </button>
            </div>
    </form>

</div>

<br>

@stop

resources/views/Jornadas/index.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Jornadas </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ ('/intruccionesjornadas') }}"> Crear una nueva jornada </a> <!-- Redirección al mecanismo de creación de jornadas. -->
        </div>
    </div>
</div>

<br>
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="row">
    <table class="table table-striped table-bordered">
        <tr>
            <th> Curso relacionado </th>
            <th> Inicio </th>
            <th> Fin </th>
            <th> Número de sesiones </th>
            <th> Número de expediente </th>
            <th> Horario </th>
            <th> Docente </th>
            <th> Centro </th>
            <th> Aula </th>
            <th> Opciones </th>
        </tr>
        @foreach ($jornadas as $jornada)
        <tr>
            <td> {{$cursos[$jornada->cursos_id -1]->nombre}} </td>
            <td> {{$jornada->fecha_ini}} </td>
            <td> {{$jornada->fecha_fin}} </td>
            <td> {{$jornada->num_sesiones}} </td>
            <td> {{$jornada->num_expediente}} </td>
            <td> {{$jornada->horario}} </td>
            <td> {{$docentes[$jornada->docentes_id - 1]->nombre}} {{$docentes[$jornada->docentes_id - 1]->apellido_1}} {{$docentes[$jornada->docentes_id - 1]->apellido_2}}</td>
            <td> {{$centros[$jornada->centros_id - 1]->nombre }} </td>
            <td> {{$aulas[$jornada->aulas_id - 1]->num}}</td>
            <td>

                <form method="POST" action="{{ url('/Jornadas/' .$jornada->id) }}" style="display:inline">

                    <a class="btn btn-success" href="{{ route('Jornadas.edit',$jornada->id) }}"> Editar </a>

                    @method('DELETE')

                    @csrf

                    @include('Jornadas.destroy')

                    <a href="" data-target="#modal-delete-{{$jornada->id}}" data-toggle="modal" class="btn btn-danger">Eliminar</a>

                    <a class="btn btn-info" href="{{ route('Jornadas.show',$jornada->id) }}"> Ver detalles </a>

                </form>
            </td>
        </tr>
        @endforeach
    </table>
</div>

@endsection

resources/views/Jornadas/previous.blade.php
@extends('layouts.nosidebar')

@section('content')

<div class="container">
    <div class="row">
        <div class="card">
            <div class="card-header">
                <h5> Creación de jornadas </h5>
            </div>
            <div class="card-body">
                <h5 class="card-title"> Instrucciones para la creación de jornadas </h5>
                <p class="card-text"> Para la creación de nuevas jornadas es necesario tener registrada previamente la información relacionada con la misma.
                    En las siguientes secciones podrán realizarse las consultas y gestiones necesarias para continuar con el proceso, todas estas gestiones se
                    abren en una nueva pestaña del navegador, una vez finalizado el proceso vuelva a esta pestaña para realizar la creación de la jornada. </p>
            </div>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="card text-white bg-dark mb-3 col-3">
            <div class="card-body">
                <h5 class="card-title"> Docentes </h5>
                <p class="card-text"> Gestión del profesorado que imparte los cursos en colaboración con la empresa. También es posible
                    gestionar sus titulaciones. </p>
                <a href="{{ url('Docentes') }}" target="_blank" class="btn btn-primary"> Consultar </a>
                <a href="{{ route('Docentes.create') }}" target="_blank" class="btn btn-primary"> Registrar </a>
            </div>
        </div>
        <div class="card text-white bg-success mb-3 col-3">
            <div class="card-body">
                <h5 class="card-title"> Cursos </h5>
                <p class="card-text"> Gestión de los cursos impartidos por la empresa.</p>
                <br><br><br>
                <a href="{{ url('Cursos') }}" target="_blank" class="btn btn-primary"> Consultar </a>
                <a href="{{ route('Cursos.create') }}" target="_blank" class="btn btn-primary"> Registrar </a>
            </div>
        </div>
        <div class="card text-white bg-dark mb-3 col-3">
            <div class="card-body">
                <h5 class="card-title"> Centros </h5>
                <p class="card-text"> Gestión de los centros en los que se imparten los cursos y se celebran estas jornadas. También es posible
                    gestionar las aulas de los centros.</p>
                <a href="{{ url('Centros') }}" target="_blank" class="btn btn-primary"> Consultar </a>
                <a href="{{ route('Centros.create') }}" target="_blank" class="btn btn-primary"> Registrar </a>
            </div>
        </div>
        <div class="card text-white bg-success mb-3 col-3">
            <div class="card-body">
                <h5 class="card-title"> Alumnos </h5>
                <p class="card-text"> Gestión de los alumnos que participan en cada curso o que han participado alguna vez en un curso impartido.</p>
                <br>
                <a href="{{ url('Alumnos') }}" target="_blank" class="btn btn-primary"> Consultar </a>
                <a href="{{ url('/Alumnosmasivo') }}" target="_blank" class="btn btn-primary"> Registrar </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-12">
            <div class="card-header col-12">
                <h5 class="card-title"> Proceder a la creación de jornadas </h5>
            </div>
            <div class="card-body">
                <p class="card-text"> Si toda la información necesaria ya está registrada continúe mediante el siguiente enlace. </p>
                <a href="{{ route('Jornadas.create') }}" class="btn btn-success col-12"> Registrar nueva jornada de la empresa </a>
            </div>
        </div>
    </div>
</div>

@endsection