routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Controladores del apartado CRUD.
use App\Http\Controllers\JornadasController;
use App\Http\Controllers\DocentesController;
use App\Http\Controllers\CentrosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\AlumnosController;
use App\Http\Controllers\EmpresasController;
use App\Http\Controllers\AulasController;
use App\Http\Controllers\SesionesController;
use App\Http\Controllers\TitulacionesController;
use App\Http\Controllers\Alumnos_Empresas_JornadasController;
use App\Http\Controllers\PDFController;


//Controlador del calendario. 
use App\Http\Controllers\FullCalendarController;

//Controlador necesario para la parte de importación y exportación. 
use App\Http\Controllers\ImportExportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Redireccionamiento al inicio en caso de error 404. 
Route::fallback(function () {

    return redirect('/inicio');

});
// Página inicial de nuestra aplicación: deriva en gestión de datos y en calendario. 
Route::get('/inicio', function () {
    return view('home');
});

// Página previa a la gestión de las jornadas y vinculación, permite gestionar información necesaria. 
Route::get('/intruccionesjornadas', function () {
    return view('Jornadas.previous');
});

// Control de importación y exportación, usado en ambos apartados de la aplicación. 
Route::get('Alumnosmasivo', [ImportExportController::class, 'importExportView']);
Route::get('export', [ImportExportController::class, 'export'])->name('export');
Route::post('import', [ImportExportController::class, 'import'])->name('import');

// Apartado 1 de la aplicación: gestión de datos, se compone de una vista inicial, que nos mete en el index de las tablas y en consultas seleccionadas. 
Route::get('/gestiondedatos', function () {
    return view('data');
});
// Para el funcionamiento de todo el método CRUD de los modelos y las diferentes consultas es necesario la utilización de sus controladores y rutas específicas. 
Route::resource('Jornadas', JornadasController::class);
Route::resource('Docentes', DocentesController::class);
Route::resource('Centros', CentrosController::class);
Route::resource('Cursos', CursosController::class);
Route::resource('Alumnos', AlumnosController::class);
Route::resource('Empresas', EmpresasController::class);
Route::resource('Aulas', AulasController::class);
Route::resource('Sesiones', SesionesController::class);
Route::resource('Titulaciones', TitulacionesController::class);
Route::resource('Alumnos_Empresas_Jornadas', Alumnos_Empresas_JornadasController::class);
Route::get('Jornadas/select_aulas/{centro}', [FullCalendarController::class, 'sacaAulas']);

// Apartado 2 de la aplicación: calendario, se compone de una vista inicial del calendario, así como de los métodos necesarios para la creación de las jornadas y su gestión. 
Route::get('/calendario', function () {
    return view('fullcalendar');
});
// Para el sistema de exportación a PDF es necesario un paquete extra.
Route::get('cartel/{id}', [PDFController::class, 'cartel']); // Generación del cartel del curso. 
Route::get('material/{id}', [PDFController::class, 'material']); // Generación del documento de material del curso. 
Route::get('diplomas/{id}', [PDFController::class, 'diplomas']); // Generación de los diplomas del curso. 
Route::get('evaluacion/{id}', [PDFController::class, 'evaluacion']); // Generación del control de aptos.
Route::get('asistencia/{id}', [PDFController::class, 'asistencia']); // Generación del control de asistencia del curso.  
Route::get('fotosRGD/{id}', [PDFController::class, 'fotosRGD']); // Generación del documento de autorización de imágenes.
Route::get('registroalumno/{id}', [PDFController::class, 'registroalumno']); // Generación del documento de registro del alumno. 

app/Models/Aulas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Aulas extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [

        'id',

        'num',

        'aforo',

        'equipo',

        'descripcion',

        'centros_id'

    ];

    /**
     * 
     * Se establece una relación 1:N con los centros. 
     * 
     */
    public function Centros()
    {
        return $this->belongsTo(Centros::class);
    }

    /**
     * 
     * Se establece una relación 1:N con las jornadas. 
     * 
     */
    public function Jornadas()
    {
        return $this->belongsTo(Jornadas::class);
    }
}

app/Http/Controllers/AulasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Aulas;
use App\Models\Centros;
use Illuminate\Http\Request;

class AulasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect('/inicio');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        $centros = Centros::all();

        return view('Aulas.create',  ['centros' => $centros]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Aulas::create($request->all());

        return redirect()->route('Centros.index')->with('success', 'Nuevo centro dado de alta.');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Aulas  $aulas
     * @return \Illuminate\Http\Response
     */
    public function show(Aulas $aulas)
    {
        return redirect('/inicio');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $aula = Aulas::findOrFail($id);

        $centros = Centros::all();

        return view('Aulas.edit', ['aula' => $aula], ['centros' => $centros]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $data = array_slice($request->all(), 2);

        Aulas::whereId($id)->update($data);

        $request->session()->flash('correcto', 'Se ha editado el registro.');

        return redirect('Centros');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Aulas  $aulas
     * @param  int  $id
     * @return \Illuminate\Http\Response
     * @param  \Illuminate\Http\Request  $request
     */
    public function destroy($id, Request $request)
    {
        Aulas::where('id', $id)->delete();

        $request->session()->flash('correcto', 'Se ha borrado el registro.');

        return redirect('Centros');
        
    }
}

resources/views/Aulas/create.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Dar de alta un aula. </h2>
        </div>
    </div>
</div>

<br>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('Aulas.store') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Número del aula:</strong>
                <input type="text" name="num" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong> Aforo:</strong>
                <input type="text" name="aforo" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong> Equipo:</strong>
                <input type="text" name="equipo" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong> Descripción:</strong>
                <input type="text" name="descripcion" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
                <label for="cars">Elige un centro:</label>
                <select name="centros_id" id="centros_id">
                    @foreach ($centros as $centro)
                    <option value="{{ $centro->id }}"> {{ $centro->nombre }}</option>
                    @endforeach
                </select>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary"> Dar de alta </button>
        </div>
    </div>


</form>

@endsection

resources/views/Aulas/destroy.blade.php
<div class="modal" tabindex="-1" role="dialog" id="modal-delete-{{$aula->id}}">
    <form method="POST" action="{{url('/Aulas/delete').'/'.$aula->id}}" style="display:inline">
        @method('DELETE')
        @csrf
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Eliminar registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p> El registro puede tener jornadas asociadas y se perderá información sobre ellas ¿Está seguro de querer borrar este centro? </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/Aulas/edit.blade.php
@extends('layouts.main')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Modificando el aula número {{ $aula->num }}. </h2>
        </div>
    </div>
</div>

<div class="row" style="margin-top:40px">
    <form method="POST" enctype="multipart/form-data" action="{{url('Aulas/'.$aula->id)}}" style="display:inline">
        {{-- TODO: Abrir el formulario e indicar el método POST --}}
        @method('PUT')
        {{-- TODO: Protección contra CSRF --}}
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Número del aula:</strong>
                    <input type="text" name="num" class="form-control" value="{{ $aula->num }}" >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong> Aforo:</strong>
                    <input type="text" name="aforo" class="form-control" value="{{ $aula->aforo }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong> Equipo:</strong>
                    <input type="text" name="equipo" class="form-control" value="{{ $aula->equipo }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong> Descripción:</strong>
                    <input type="text" name="descripcion" class="form-control" value="{{ $aula->descripcion }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <label for="cars">Elija el centro al que pertenece:</label>
                <select name="centros_id" id="centros_id">
                    @foreach ($centros as $centro)
                    <option value="{{ $centro->id }}"> {{ $centro->nombre }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary"> Realizar la modificación </button>
            </div>
    </form>

</div>

<br>

@stop